### ISSUE TITLE
Page not displayed

### ISSUE THREAD

**Issue by shree3176** [shree3176/Blog#5]
![image](https://user-images.githubusercontent.com/4025226/37393351-da01f9dc-2796-11e8-8eb2-faca9da148bb.png)
------------------------------------------------------------------------------------------------------
Application logs
```
2018-03-12T05:17:25.800255+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/" host=hichkipichki.herokuapp.com request_id=4a7b402a-2497-43ea-b987-4c673f02e753 fwd="120.138.124.154" dyno= connect= service= status=502 bytes= protocol=https
2018-03-12T05:17:26.191049+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/favicon.ico" host=hichkipichki.herokuapp.com request_id=02dd953b-cf1e-4eb1-ba4e-33ecc3d314e9 fwd="120.138.124.154" dyno= connect= service= status=502 bytes= protocol=https
2018-03-12T09:56:14.515533+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/" host=hichkipichki.herokuapp.com request_id=cb19dbcf-31a6-4ed4-bcaa-c699164aac9f fwd="120.138.124.154" dyno= connect= service= status=502 bytes= protocol=https
2018-03-12T09:56:15.228351+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/favicon.ico" host=hichkipichki.herokuapp.com request_id=e1744e39-ddb8-4b7c-8263-f05d8e9f6961 fwd="120.138.124.154" dyno= connect= service= status=502 bytes= protocol=https
2018-03-14T08:36:47.224220+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/" host=hichkipichki.herokuapp.com request_id=cd014d21-f35b-42cb-a905-9193b0743042 fwd="120.138.124.154" dyno= connect= service= status=502 bytes= protocol=https
2018-03-14T08:36:47.867499+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/favicon.ico" host=hichkipichki.herokuapp.com request_id=5b8409a7-cedc-4635-9620-261f1cfd9bcb fwd="120.138.124.154" dyno= connect= service= status=502 bytes= protocol=https
2018-03-14T09:06:40.975675+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=hichkipichki.herokuapp.com request_id=2bdf2f5d-968b-449c-bb54-272e547b5700 fwd="120.138.124.154" dyno= connect= service= status=503 bytes= protocol=https
2018-03-14T09:06:41.587644+00:00 heroku[router]: at=**error code=H14** desc="No web processes running" method=GET path="/favicon.ico" host=hichkipichki.herokuapp.com req
uest_id=d1253842-5c93-44cf-a0ae-867eca7095bd fwd="120.138.124.154" dyno= connect= service= status=503 bytes= protocol=https
2018-03-14T09:17:27.456550+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=hichkipichki.herokuapp.com request_id=8deb4b9f-31f8-48ee-a7dc-fb5ee27f37c0 fwd="120.138.124.154" dyno= connect= service= status=503 bytes= protocol=https
2018-03-14T09:17:28.215105+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=hichkipichki.herokuapp.com request_id=148bee80-1adc-4881-b79d-7fc41c924ba7 fwd="120.138.124.154" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by shree3176** [comment]
error code=H14 resolved by adding Procfile with `web: gunicorn gettingstarted.wsgi --log-file -`
and `heroku ps:scale web=1`
For Reference: [https://devcenter.heroku.com/articles/error-codes#h14-no-web-dynos-running](url)

**Comment by shree3176** [comment]
```
2018-03-14T11:39:34.760175+00:00 heroku[web.1]: State changed from crashed to starting
2018-03-14T11:39:38.642832+00:00 heroku[web.1]: Starting process with command `python sanskrity.py`
2018-03-14T11:39:41.376185+00:00 app[web.1]: Traceback (most recent call last):
2018-03-14T11:39:41.376204+00:00 app[web.1]:   File "sanskrity.py", line 7, in <module>
2018-03-14T11:39:41.376320+00:00 app[web.1]:     app = create_app(os.getenv('SANSKRITY_CONFIG'))
2018-03-14T11:39:41.376322+00:00 app[web.1]:   File "/app/app/__init__.py", line 20, in create_app
2018-03-14T11:39:41.376417+00:00 app[web.1]:     app.config.from_object(config[config_name])
2018-03-14T11:39:41.376435+00:00 app[web.1]: KeyError: 'heroku'
2018-03-14T11:39:41.503237+00:00 heroku[web.1]: Process exited with status 1
2018-03-14T11:39:41.598677+00:00 heroku[web.1]: State changed from starting to crashed
2018-03-14T11:39:41.601497+00:00 heroku[web.1]: State changed from crashed to starting
2018-03-14T11:39:45.652604+00:00 heroku[web.1]: Starting process with command `python sanskrity.py`
2018-03-14T11:39:48.707138+00:00 heroku[web.1]: State changed from starting to crashed
2018-03-14T11:39:48.683332+00:00 heroku[web.1]: Process exited with status 1
2018-03-14T11:39:48.571269+00:00 app[web.1]: Traceback (most recent call last):
2018-03-14T11:39:48.571297+00:00 app[web.1]:   File "sanskrity.py", line 7, in <module>
2018-03-14T11:39:48.571402+00:00 app[web.1]:     app = create_app(os.getenv('SANSKRITY_CONFIG'))
2018-03-14T11:39:48.571405+00:00 app[web.1]:   File "/app/app/__init__.py", line 20, in create_app
2018-03-14T11:39:48.571503+00:00 app[web.1]:     app.config.from_object(config[config_name])
2018-03-14T11:39:48.571518+00:00 app[web.1]: KeyError: 'heroku'
```

**Comment by shree3176** [comment]
```
2018-03-14T11:41:03.734964+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=hichkipichki.herokuapp.com request_id=96213fcd-1ab4-4632-a8ee-9cec7e05e47f fwd="120.138.124.154" dyno= connect= service= status=503 bytes= protocol=https
2018-03-14T11:41:04.112456+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=hichkipichki.herokuapp.com request_id=44c99e41-6c8b-40fa-bdbe-8e53a4712c0c fwd="120.138.124.154" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by shree3176** [comment]
Resolved by adding `web: gunicorn sanskrity:app`
For references:
 [https://github.com/shree3176/Blog/commit/f961873facb63560189035653d5a88a3d2c11f8d](url)
